name: cd

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: build && export
        run: npm run build && npm run export
        env:
          REACT_APP_APIKey: ${{ secrets.REACT_APP_APIKey }}
          REACT_APP_APISecret: ${{ secrets.REACT_APP_APISecret }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
