name: cd

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: npm install

      - name: echo env
        env:
          CTFL_ACCESS_TOKEN: ${{ secrets.CTFL_ACCESS_TOKEN }}
        run: |
          echo $CTFL_ACCESS_TOKEN

      - name: build && export
        run: npm run build && npm run export
        env:
          CTFL_CONTENT_TYPE_POST: ${{ secrets.CTFL_CONTENT_TYPE_POST }}
          CTFL_SPACE: ${{ secrets.CTFL_SPACE }}
          CTFL_ACCESS_TOKEN: ${{ secrets.CTFL_ACCESS_TOKEN }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: build
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          # publish_dir: ./dist
